### ISSUE TITLE
Use Math lib

### ISSUE THREAD

**Issue by wezko** [tomtom-international/speedtools#1]
For geo mMercatorPoint: Math.toDegrees() and Math.toRadians() would be nicer than DIY in the lat/lon to mercs conversion.

**Comment by rijnb** [comment]
Done. Please review: https://github.com/tomtom-international/speedtools/blob/master/geo/src/main/java/com/tomtom/speedtools/tilemap/MercatorPoint.java

**Comment by wezko** [comment]
Math.PI * ((lat + 90.0) / 360.0) would be a candidate too:

Math.toRadians(lat + 90)/2;

**Comment by rijnb** [comment]
OK, done. You can rereview.

**Comment by wezko** [comment]
On line 77, there is another one, I missed it, it is the inverse.

Change to:
final double lat = Math.toDegrees(Math.atan(Math.exp(geoY / MapConst.WORLD_RADIUS)) * 2 - 90.0;

**Comment by wezko** [comment]
[Ik kwam hierop omdat we in de Map lib op Bridge een projectiefout hadden.
Die had ik ook in mijn eigen code. Na wat studie beide opgelost.]

Weet jij of we ook een open source lib voor android hebben die bv tiles kan
weergeven, een view met controller, waar je een tileprovider in kunt
steken. Ik weet iemand die dat graag wil hebben :-)

PS mocht je nog willen map browsen: http://www.navkid.com, ik heb de
engines "af", als een jar met API, die steek ik in een Android app, dan
houd ik de NavKidt mooi gescheiden van de interactie.
Het meeste van de kaart (netwerk) is af, ik ben nog bezig de meest
noodzakelijke "faces" aan te vullen, dat zie je hier en daar wel bij
inzoomen als vreemde vormpjes. Dan alle namen uit mijn oude POI66 database
trekken en linken naar havens, kanalen, steden. POIs had ik al zoals
molens, bakens, havens, scouting. Ik heb een beeld wat de App moet doen:
weinig, maar wel goed.

[Android only, tenzij jij een manier weet (er zijn java->iOS/Android
 oplossingen, zou ideaal zijn, ook voor TT)]

Tot zover dit vage bericht.
K


2016-02-03 9:21 GMT+01:00 Rijn Buve <notifications@github.com>:

**Comment by rijnb** [comment]
Done. You can review it. NavKid: will mail.

**Comment by wezko** [comment]
I wonder if this would be even better:
final double lat = Math.toDegrees(Math.atan(Math.exp(geoY / MapConst.WORLD_RADIUS))) * 2.0 - 90.0;

**Comment by rijnb** [comment]
Done; included brackets though.
