### ISSUE TITLE
GeoPoint latitude/longitude Javadoc not in line with implementation

### ISSUE THREAD

**Issue by Joozt** [tomtom-international/speedtools#10]
Latitude/longitude description is swapped in Javadoc

https://github.com/tomtom-international/speedtools/blob/454ac092582a627849233041826962937734d1e8/geo/src/main/java/com/tomtom/speedtools/geometry/GeoPoint.java#L46

**Comment by rijnb** [comment]
Fixed. Thanks!
See commit 8973b4fe541ddfaadbf13f4429b1883a37642560
